name: Publish Connector Image
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to check out code from. Defaults to the main airbyte repo. Set this when building connectors from forked repos."
        required: false
        default: "airbytehq/airbyte"
      gitref:
        description: "The git ref to check out from the specified repository."
        required: false
        default: master
      connector:
        description: "Airbyte Connector"
        required: true
      run-tests:
        description: "Should run tests when publishing"
        required: true
        default: "true"
      comment-id:
        description: "The comment-id of the slash command. Used to update the comment with the status."
        required: false
      auto-bump-version:
        description: "after publishing, the workflow will automatically bump the connector version in definitions and generate seed spec"
        required: true
        default: "true"

jobs:
  find_valid_pat:
    name: "Find a PAT with room for actions"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      pat: ${{ steps.variables.outputs.pat }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Check PAT rate limits
        id: variables
        run: |
          ./tools/bin/find_non_rate_limited_PAT \
            ${{ secrets.AIRBYTEIO_PAT }} \
            ${{ secrets.OSS_BUILD_RUNNER_GITHUB_PAT }} \
            ${{ secrets.SUPERTOPHER_PAT }} \
            ${{ secrets.DAVINCHIA_PAT }}
  ## Gradle Build
  # In case of self-hosted EC2 errors, remove this block.
  start-publish-image-runner:
    name: Start Build EC2 Runner
    strategy:
      fail-fast: false
      matrix:
        ec2-instance-id:
          [
            "${{ github.run_id }}-${{ github.run_attempt }}-1",
            "${{ github.run_id }}-${{ github.run_attempt }}-2",
            "${{ github.run_id }}-${{ github.run_attempt }}-3",
            "${{ github.run_id }}-${{ github.run_attempt }}-4",
            "${{ github.run_id }}-${{ github.run_attempt }}-5 ",
          ]
    runs-on: ubuntu-latest
    needs: find_valid_pat
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      # ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.gitref }}
      - name: Start AWS Runner
        id: start-ec2-runner
        uses: ./.github/actions/start-aws-runner
        with:
          aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWCRET_ACCESS_KEY }}
          github-token: ${{ needs.find_valid_pat.outputs.pat }}
          label: airbyte-publisher-runner
          ec2-instance-id: ${{ matrix.ec2-instance-id }}

  stop-publish-image-runner:
    name: Stop Build EC2 Runner
    strategy:
      fail-fast: false
      matrix:
        ec2-instance-id:
          [
            "${{ github.run_id }}-${{ github.run_attempt }}-1",
            "${{ github.run_id }}-${{ github.run_attempt }}-2",
            "${{ github.run_id }}-${{ github.run_attempt }}-3",
            "${{ github.run_id }}-${{ github.run_attempt }}-4",
            "${{ github.run_id }}-${{ github.run_attempt }}-5 ",
          ]
    needs:
      - start-publish-image-runner # required to get output from the start-runner job
      # - publish-image # required to wait when the main job is done
      - find_valid_pat
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Stop EC2 runner
        uses: supertopher/ec2-github-runner@base64v1.0.10
        with:
          mode: stop
          github-token: ${{ needs.find_valid_pat.outputs.pat }}
          label: ${{ needs.start-publish-image-runner.outputs.label }}
          ec2-instance-id: ${{ matrix.ec2-instance-id }}
